services:
  app:
    path: app
    public: true
    port: 8080
    cmd: node app.js
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/test
  mongo:
    image: mongo:4.0
steps:
  - name: mongodump
    path: mongodump
    out: /dump
    cache: true
  - name: load
    service: mongo
    copy:
      - mongodump:/
    cmd: mongorestore /dump
